# Generated by Django 5.1.2 on 2024-10-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('optimized_image', models.ImageField(blank=True, null=True, upload_to='optimized/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('optimized_at', models.DateTimeField(auto_now=True)),
                ('original_size', models.IntegerField(blank=True, null=True)),
                ('optimized_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
